[package]
name = "fbapi"
version = "0.1.0"
authors = ["Thomas Cheng <thomascheng1998@googlemail.com>"]

[dependencies]

hyper = "*"
hyper-native-tls = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"
