[package]
name = "fbapi"
version = "0.1.0"
authors = ["Thomas Cheng <thomascheng1998@googlemail.com>"]

[dependencies]

hyper = "*"
hyper-native-tls = "*"

serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
